---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: Default
    inherits: 
    description: 
  fields:
  - sp_api_ref:
      value: _vti_bin/ListData.svc
  - sp_list_name:
      value: MyOrgList
  - sp_password:
      value: v2:{jEwaINXpX4GbFz/laheqYrAgrUSYr1JTiYlTU6/h2hg=}
  - sp_username:
      value: cloud_svc_acct
  - sp_site:
      value: MyOrgSite
  - sp_server:
      value: myorgsharepoint.mydomain.com
  - sp_url_prefix:
      value: http
